## Pandas

pandas is one of the world's most popular Python library, used for everything from data manipulation to data analysis.

pandas is used for **tabular data** (data which has rows and columns)

### What can pandas do for us?

- Load Tabular Data 
- Search For Particular rows and columns
- Calculate all kinds of statistical methods.
-  Combine data from multiple sources

Run the following cell:

In [1]:
!pip3 install pandas

Requirement already satisfied: pandas in /Users/negarvahid/.local/share/virtualenvs/negarvahid-mIme9Lir/lib/python3.7/site-packages (1.2.1)
Requirement already satisfied: python-dateutil>=2.7.3 in /Users/negarvahid/.local/share/virtualenvs/negarvahid-mIme9Lir/lib/python3.7/site-packages (from pandas) (2.8.1)
Requirement already satisfied: pytz>=2017.3 in /Users/negarvahid/.local/share/virtualenvs/negarvahid-mIme9Lir/lib/python3.7/site-packages (from pandas) (2021.1)
Requirement already satisfied: numpy>=1.16.5 in /Users/negarvahid/.local/share/virtualenvs/negarvahid-mIme9Lir/lib/python3.7/site-packages (from pandas) (1.20.0)
Requirement already satisfied: six>=1.5 in /Users/negarvahid/.local/share/virtualenvs/negarvahid-mIme9Lir/lib/python3.7/site-packages (from python-dateutil>=2.7.3->pandas) (1.12.0)

**Importing pandas:**

In [2]:
import pandas as pd

**How do I load a CSV file using pandas?**

Let's mess around with a **Spotify** Dataset.

In [3]:
df = pd.read_csv("top50.csv")
#CSV : Comma-separated values

**Viewing df**

In [4]:
df

,Unnamed: 0,Track.Name,Artist.Name,Genre,Beats.Per.Minute,Energy,Danceability,Loudness..dB..,Liveness,Valence.,Length.,Acousticness..,Speechiness.,Popularity
0,1,Seï¿½orita,Shawn Mendes,canadian pop,117,55,76,-6,8,75,191,4,3,79
1,2,China,Anuel AA,reggaeton flow,105,81,79,-4,8,61,302,8,9,92
2,3,boyfriend (with Social House),Ariana Grande,dance pop,190,80,40,-4,16,70,186,12,46,85
3,4,Beautiful People (feat. Khalid),Ed Sheeran,pop,93,65,64,-8,8,55,198,12,19,86
4,5,Goodbyes (Feat. Young Thug),Post Malone,dfw rap,150,65,58,-4,11,18,175,45,7,94
5,6,I Don't Care (with Justin Bieber),Ed Sheeran,pop,102,68,80,-5,9,84,220,9,4,84
6,7,Ransom,Lil Tecca,trap music,180,64,75,-6,7,23,131,2,29,92
7,8,How Do You Sleep?,Sam Smith,pop,111,68,48,-5,8,35,202,15,9,90
8,9,Old Town Road - Remix,Lil Nas X,country rap,136,62,88,-6,11,64,157,5,10,87
9,10,bad guy,Billie Eilish,electropop,135,43,70,-11,10,56,194,33,38,95
10,11,Callaita,Bad Bunny,reggaeton,176,62,61,-5,24,24,251,60,31,93
11,12,Loco Contigo (feat. J. Balvin & Tyga),DJ Snake,dance pop,96,71,82,-4,15,38,185,28,7,86
12,13,Someone You Loved,Lewis Capaldi,pop,110,41,50,-6,11,45,182,75,3,88
13,14,Otro Trago - Remix,Sech,panamanian pop,176,79,73,-2,6,76,288,7,20,87
14,15,Money In The Grave (Drake ft. Rick Ross),Drake,canadian hip hop,101,50,83,-4,12,10,205,10,5,92
15,16,No Guidance (feat. Drake),Chris Brown,dance pop,93,45,70,-7,16,14,261,12,15,82
16,17,LA CANCIï¿½N,J Balvin,latin,176,65,75,-6,11,43,243,15,32,90
17,18,Sunflower - Spider-Man: Into the Spider-Verse,Post Malone,dfw rap,90,48,76,-6,7,91,158,56,5,91
18,19,Lalala,Y2K,canadian hip hop,130,39,84,-8,14,50,161,18,8,88
19,20,Truth Hurts,Lizzo,escape room,158,62,72,-3,12,41,173,11,11,91
20,21,Piece Of Your Heart,MEDUZA,pop house,124,74,68,-7,7,63,153,4,3,91
21,22,Panini,Lil Nas X,country rap,154,59,70,-6,12,48,115,34,8,91
22,23,No Me Conoce - Remix,Jhay Cortez,reggaeton flow,92,79,81,-4,9,58,309,14,7,83
23,24,Soltera - Remix,Lunay,latin,92,78,80,-4,44,80,266,36,4,91
24,25,bad guy (with Justin Bieber),Billie Eilish,electropop,135,45,67,-11,12,68,195,25,30,89
25,26,If I Can't Have You,Shawn Mendes,canadian pop,124,82,69,-4,13,87,191,49,6,70
26,27,Dance Monkey,Tones and I,australian pop,98,59,82,-6,18,54,210,69,10,83
27,28,It's You,Ali Gatie,canadian hip hop,96,46,73,-7,19,40,213,37,3,89
28,29,Con Calma,Daddy Yankee,latin,94,86,74,-3,6,66,193,11,6,91
29,30,QUE PRETENDES,J Balvin,latin,93,79,64,-4,36,94,222,3,25,89
30,31,Takeaway,The Chainsmokers,edm,85,51,29,-8,10,36,210,12,4,84
31,32,7 rings,Ariana Grande,dance pop,140,32,78,-11,9,33,179,59,33,89
32,33,0.958333333333333,Maluma,reggaeton,96,71,78,-5,9,68,176,22,28,89
33,34,The London (feat. J. Cole & Travis Scott),Young Thug,atl hip hop,98,59,80,-7,13,18,200,2,15,89
34,35,Never Really Over,Katy Perry,dance pop,100,88,77,-5,32,39,224,19,6,89
35,36,Summer Days (feat. Macklemore & Patrick Stump ...,Martin Garrix,big room,114,72,66,-7,14,32,164,18,6,89
36,37,Otro Trago,Sech,panamanian pop,176,70,75,-5,11,62,226,14,34,91
37,38,Antisocial (with Travis Scott),Ed Sheeran,pop,152,82,72,-5,36,91,162,13,5,87
38,39,Sucker,Jonas Brothers,boy band,138,73,84,-5,11,95,181,4,6,80
39,40,"fuck, i'm lonely (with Anne-Marie) - from ï¿½13 ...",Lauv,dance pop,95,56,81,-6,6,68,199,48,7,78
40,41,Higher Love,Kygo,edm,104,68,69,-7,10,40,228,2,3,88
41,42,You Need To Calm Down,Taylor Swift,dance pop,85,68,77,-6,7,73,171,1,5,90
42,43,Shallow,Lady Gaga,dance pop,96,39,57,-6,23,32,216,37,3,87
43,44,Talk,Khalid,pop,136,40,90,-9,6,35,198,5,13,84
44,45,Con Altura,ROSALï¿½A,r&b en espanol,98,69,88,-4,5,75,162,39,12,88
45,46,One Thing Right,Marshmello,brostep,88,62,66,-2,58,44,182,7,5,88
46,47,Te Robarï¿½,Nicky Jam,latin,176,75,67,-4,8,80,202,24,6,88
47,48,Happier,Marshmello,brostep,100,79,69,-3,17,67,214,19,5,88
48,49,Call You Mine,The Chainsmokers,edm,104,70,59,-6,41,50,218,23,3,88
49,50,Cross Me (feat. Chance the Rapper & PnB Rock),Ed Sheeran,pop,95,79,75,-6,7,61,206,21,12,82

**Inspecting df**

In [7]:
df.head()

,Unnamed: 0,Track.Name,Artist.Name,Genre,Beats.Per.Minute,Energy,Danceability,Loudness..dB..,Liveness,Valence.,Length.,Acousticness..,Speechiness.,Popularity
0,1,Seï¿½orita,Shawn Mendes,canadian pop,117,55,76,-6,8,75,191,4,3,79
1,2,China,Anuel AA,reggaeton flow,105,81,79,-4,8,61,302,8,9,92
2,3,boyfriend (with Social House),Ariana Grande,dance pop,190,80,40,-4,16,70,186,12,46,85
3,4,Beautiful People (feat. Khalid),Ed Sheeran,pop,93,65,64,-8,8,55,198,12,19,86
4,5,Goodbyes (Feat. Young Thug),Post Malone,dfw rap,150,65,58,-4,11,18,175,45,7,94

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        50 non-null     int64
 1   Track.Name        50 non-null     object
 2   Artist.Name       50 non-null     object
 3   Genre             50 non-null     object
 4   Beats.Per.Minute  50 non-null     int64
 5   Energy            50 non-null     int64
 6   Danceability      50 non-null     int64
 7   Loudness..dB..    50 non-null     int64
 8   Liveness          50 non-null     int64
 9   Valence.          50 non-null     int64
 10  Length.           50 non-null     int64
 11  Acousticness..    50 non-null     int64
 12  Speechiness.      50 non-null     int64
 13  Popularity        50 non-null     int64
dtypes: int64(11), object(3)
memory usage: 5.6+ KB

## Selecting Data

### Subsetting A Column

In [9]:
df['Genre']

0         canadian pop
1       reggaeton flow
2            dance pop
3                  pop
4              dfw rap
5                  pop
6           trap music
7                  pop
8          country rap
9           electropop
10           reggaeton
11           dance pop
12                 pop
13      panamanian pop
14    canadian hip hop
15           dance pop
16               latin
17             dfw rap
18    canadian hip hop
19         escape room
20           pop house
21         country rap
22      reggaeton flow
23               latin
24          electropop
25        canadian pop
26      australian pop
27    canadian hip hop
28               latin
29               latin
30                 edm
31           dance pop
32           reggaeton
33         atl hip hop
34           dance pop
35            big room
36      panamanian pop
37                 pop
38            boy band
39           dance pop
40                 edm
41           dance pop
42           dance pop
43                 pop
44      r&b en espanol
45             brostep
46               latin
47             brostep
48                 edm
49                 pop
Name: Genre, dtype: object

### Subsetting multiple columns

In [11]:
df[['Genre', 'Energy']].head()

            Genre  Energy
0    canadian pop      55
1  reggaeton flow      81
2       dance pop      80
3             pop      65
4         dfw rap      65

- The `.loc` operator

Although selecting data with `[]` works, it's not necessarily the best way. 

Pandas' official documentation :


>The Python and NumPy indexing operators [] and attribute operator . provide quick and easy access to pandas data structures across a wide range of use cases. This makes interactive work intuitive, as thereâs little new to learn if you already know how to deal with Python dictionaries and NumPy arrays. However, since the type of the data to be accessed isnât known in advance, directly using standard operators has some optimization limits. For production code, we recommended that you take advantage of the optimized pandas data access methods exposed in this chapter.

In [12]:
# select a row
df.loc[12]

Unnamed: 0                         13
Track.Name          Someone You Loved
Artist.Name             Lewis Capaldi
Genre                             pop
Beats.Per.Minute                  110
Energy                             41
Danceability                       50
Loudness..dB..                     -6
Liveness                           11
Valence.                           45
Length.                           182
Acousticness..                     75
Speechiness.                        3
Popularity                         88
Name: 12, dtype: object

In [13]:
# select a cell
df.loc[12, 'Track.Name']

'Someone You Loved'

In [14]:
#select a column
df.loc[:, 'Track.Name'].head()

0                           Seï¿½orita
1                              China
2      boyfriend (with Social House)
3    Beautiful People (feat. Khalid)
4        Goodbyes (Feat. Young Thug)
Name: Track.Name, dtype: object

Remeber how we could perform slicing on lists? 
We can do the same thing with `.loc`!

In [15]:
# rows with label 2 to 5
df.loc[10:15]

,Unnamed: 0,Track.Name,Artist.Name,Genre,Beats.Per.Minute,Energy,Danceability,Loudness..dB..,Liveness,Valence.,Length.,Acousticness..,Speechiness.,Popularity
10,11,Callaita,Bad Bunny,reggaeton,176,62,61,-5,24,24,251,60,31,93
11,12,Loco Contigo (feat. J. Balvin & Tyga),DJ Snake,dance pop,96,71,82,-4,15,38,185,28,7,86
12,13,Someone You Loved,Lewis Capaldi,pop,110,41,50,-6,11,45,182,75,3,88
13,14,Otro Trago - Remix,Sech,panamanian pop,176,79,73,-2,6,76,288,7,20,87
14,15,Money In The Grave (Drake ft. Rick Ross),Drake,canadian hip hop,101,50,83,-4,12,10,205,10,5,92
15,16,No Guidance (feat. Drake),Chris Brown,dance pop,93,45,70,-7,16,14,261,12,15,82

In [16]:
# columns between Track.Name and Genre
df.loc[:, 'Track.Name':'Genre'].head()

                        Track.Name    Artist.Name           Genre
0                         Seï¿½orita   Shawn Mendes    canadian pop
1                            China       Anuel AA  reggaeton flow
2    boyfriend (with Social House)  Ariana Grande       dance pop
3  Beautiful People (feat. Khalid)     Ed Sheeran             pop
4      Goodbyes (Feat. Young Thug)    Post Malone         dfw rap

â¨**Task**

- Open `tweets.csv` using pandas into a dataframe called `new`. 
- Inspect the dataset.
- Research how you can drop the NaN values. 
- Select the `text` column.
- Select the 100th row using `.loc`
- Select the cell on the 29th row on the **text** column.

In [17]:
#INSERT YOUR CODE HERE
new = pd.read_csv("tweets.csv")
new.head()

   id keyword location                                               text
0   0     NaN      NaN                 Just happened a terrible car crash
1   2     NaN      NaN  Heard about #earthquake is different cities, s...
2   3     NaN      NaN  there is a forest fire at spot pond, geese are...
3   9     NaN      NaN           Apocalypse lighting. #Spokane #wildfires
4  11     NaN      NaN      Typhoon Soudelor kills 28 in China and Taiwan

In [18]:
new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3263 entries, 0 to 3262
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        3263 non-null   int64
 1   keyword   3237 non-null   object
 2   location  2158 non-null   object
 3   text      3263 non-null   object
dtypes: int64(1), object(3)
memory usage: 102.1+ KB

In [19]:
new.dropna()

,id,keyword,location,text
15,46,ablaze,London,Birmingham Wholesale Market is ablaze BBC News...
16,47,ablaze,Niall's place | SAF 12 SQUAD |,@sunkxssedharry will you wear shorts for race ...
17,51,ablaze,NIGERIA,#PreviouslyOnDoyinTv: Toke MakinwaÂÃÂªs marriag...
18,58,ablaze,Live On Webcam,Check these out: http://t.co/rOI2NSmEJJ http:/...
19,60,ablaze,"Los Angeles, Califnordia",PSA: IÂÃÂªm splitting my personalities.\n\n?? t...
...,...,...,...,...
3246,10804,wrecked,Love Reiss,@yakubOObs think he deactivated because his no...
3247,10806,wrecked,Seattle Washington,RT CNBC '3 words from Disney CEO Bob Iger wrec...
3248,10807,wrecked,Acey mountain islanddÃ¥ÃTorontoÃ¥Ã,Smackdown tyme this should put me in a good mo...
3249,10816,wrecked,los angeles,@thrillhho jsyk I haven't stopped thinking abt...
3250,10820,wrecked,"Brussels, Belgium",@stighefootball Begovic has been garbage. He g...

In [20]:
new['text']

0                      Just happened a terrible car crash
1       Heard about #earthquake is different cities, s...
2       there is a forest fire at spot pond, geese are...
3                Apocalypse lighting. #Spokane #wildfires
4           Typhoon Soudelor kills 28 in China and Taiwan
                              ...
3258    EARTHQUAKE SAFETY LOS ANGELES ÂÃÃ SAFETY FASTE...
3259    Storm in RI worse than last hurricane. My city...
3260    Green Line derailment in Chicago http://t.co/U...
3261    MEG issues Hazardous Weather Outlook (HWO) htt...
3262    #CityofCalgary has activated its Municipal Eme...
Name: text, Length: 3263, dtype: object

In [21]:
new.loc[100]

id                                                        339
keyword                                           annihilated
location                                                  NaN
text        BROOO HE JUST GOT ANNIHILATED https://t.co/UR7...
Name: 100, dtype: object

In [23]:
new.loc[29, 'text']

'Accident cleared in #PaTurnpike on PATP EB between PA-18 and Cranberry slow back to #traffic http://t.co/SL0Oqn0Vyr'